#This query returns a list of all classes in the suite and their annotations. It may be used to confirm the required elements are uniformly applied, as well as to extract the contents of the ontology and place them in a spreadsheet for review outside an ontology editor.
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX cco: <http://www.ontologyrepository.com/CommonCoreOntologies/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX obo: <http://purl.obolibrary.org/obo/>

SELECT ?URI ?label ?definition ?parentclassLabel ?parentclasslabel ?equivalentClass ?FOLaxiom ?comment
WHERE
{?URI rdfs:subClassOf ?parentclass.
?parentclass rdfs:label ?parentclassLabel.
OPTIONAL {?URI rdfs:label ?label}
OPTIONAL {?URI obo:IAO_0000602 ?FOLaxiom}
OPTIONAL {?URI cco:definition ?definition}
OPTIONAL {?URI rdfs:comment ?comment}
OPTIONAL {?URI owl:equivalentClass ?equivalentClass}
FILTER(regex(str(?URI), "iof_"))
}
